emit:
  - "@typespec/openapi3"
  - "@typespec/http-client-js"
  - "@typespec/http-server-js"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.1.0
  "@typespec/http-client-js":
    emitter-output-dir: "{output-dir}/clients/js"
  "@typespec/http-server-js":
    emitter-output-dir: "{output-dir}/server/js"
